spring:
  application:
    name: rs-gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://internal-order-service
          predicates:
            - Path=/api/order-service
        - id: payment-service
          uri: lb://internal-payment-service
          predicates:
            - Path=/api/payment-service
        - id: request-header
          uri: https://httpbin.org
          predicates:
            - Path=/get/**
          filters:
            - AddRequestHeader=My-Header-Good,Good
            - AddRequestHeader=My-Header-Remove,Remove
            - AddRequestParameter=var, good
            - AddRequestParameter=var2, remove
            - MapRequestHeader=My-Header-Good, My-Header-Bad
            - MapRequestHeader=My-Header-Set, My-Header-Bad
            - SetRequestHeader=My-Header-Set, Set
            - RemoveRequestHeader=My-Header-Remove
            - RemoveRequestParameter=var2


