version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  slack: circleci/slack@3.4.2

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results

jobs:
  notifytest:
    executor: orb-tools/ubuntu
    steps:
      - run: exit 0 #toggle this to force success or status for testing
      - slack/notify:
          message: "notification test for the Slack orb, triggered by *<https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commit/${CIRCLE_SHA1}|commit ${CIRCLE_SHA1}>* on ${CIRCLE_PROJECT_REPONAME}'s *${CIRCLE_BRANCH}* branch (<https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|workflow here>)"
          color: "#f4aa42"
          mentions: "${ORBS_USER_GROUP_UUID}"
